config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"

  resources :lists do
    resources :bookmarks, only: [:index, :new, :create]
  end

  resources :bookmarks, only: [:create] do
    resources :movies, only: [:index]
  end

  resources :bookmarks, only: [:destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :overview, presence: true
  validates :title, uniqueness: true
  validates :overview, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:create]

  # def index
  # end

  # def show
  # end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @movies = Movie.all
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  # end

  # def update
  # end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show;
    @bookmarks = Bookmark.all.where('list_id = ?', params[:id].to_i)
  end

  def new
    @list = List.new()
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  # end

  # def update
  # end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mx-auto border bg-light p-3 m-3">
<h1>Ajouter un film</h1>

<div class="border p-3">
<h5> Films disponibles</h5>
<ul class="list-inline">
<% @movies.each do |movie| %>
    <li class="list-inline-item"><%=movie.title%></li>
<% end %>
</ul>
</div>
<br>

<%= simple_form_for [@movie, @list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, :collection => @movies, include_blank:  false, include_hidden: true %>
  <%= f.submit "Ajouter un film", class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1>Save any kind of movies</h1>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag 'popcorn.jpg' %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <div class="d-flex justify-content-between">
          <li class="nav-item active p-2">
            <%= link_to 'Accéder à mes listes', root_path %>
          </li>
          <li class="nav-item p-2">
            <%= link_to 'Nouvelle liste', new_list_path %>
          </li>
          <li class="nav-item dropdown">
          </li>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render partial: "layouts/banner" %>

<div class="container p-3 m-3 border bg-light  mx-auto">

<h3>Mes sélections</h3>

<div class="container">
  <div class="row justify-content-between ">
      <% @lists.each do |list| %>
          <%= render partial: "pages/card_list", locals: {list: list} %>
      <% end %>
</div>
</div>
</div>

app/views/lists/new.html.erb
<div class="container p-3 m-3 bg-light border">
<h2>Nouvelle sélection</h2>
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add a list", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="container p-3 m-3 bg-light border">
<h1><%= @list.name %>  </h1>
<br>

<%= @list.photo.attached? ? cl_image_tag( @list.photo.key, height: 300, width: 400, crop: :fill) : ""%>
<% if @bookmarks.count > 0 %>
<h2> Ma sélection (<%= @bookmarks.count %>) </h2>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <br>
    <ul class="list-inline">
    <li class="list-inline-item"><%=bookmark.comment%></li>
    <li class="list-inline-item"><%=bookmark.movie.title%></li>
    <li class="list-inline-item"><%=bookmark.list.name%></li>
    </ul>
    <%= link_to 'Supprimer de la sélection', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <br>
  <% end %>
</ul>
<% else %>
<h2> Aucun film ajouté pour le moment </h2>
<% end %>


<%= link_to 'Ajouter un film', new_list_bookmark_path(@list, @bookmark), class: "btn btn-primary" %>
</div>

app/views/pages/_card_list.html.erb
<div class="card mb-3 col-3 p-0 m-0 d-flex flex-column justify-content-between">
  <%= list.photo.attached? ? cl_image_tag(list.photo.key, :height=>200, :gravity=>"auto", :crop=>"fill") :  image_tag('pellicule.jpg', height: 200) %>
  <div class="card-body d-flex flex-column justify-content-between">
    <h4 class="card-title"><strong><%= list.name %></strong></h4>
    <p class="card-text"><i>Nombre de films : <%= list.bookmarks.count %></i></p>
    <div class="d-flex justify-content-between mt-auto border-top pt-2">
      <%= link_to 'Voir la sélection', list_path(list) %>
      <%= link_to 'Supprimer', list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  </div>
</div>